name: Scraping contests

on:
  schedule:
    # Roda 08h da manha (pelo horario de brasilia)
    - cron: '0 11 * * *'
  workflow_dispatch: 


jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3


      - name: Setup python
        uses: actions/setup-python@v4
        with:
            python-version: '3.14'
      
      - name: Install dependencys
        run: pip3 install -r requirements.txt

      - name: Install Playwright and Firefox
        run: |
            playwright install firefox
            playwright install-deps firefox

      - name: Run worker
        env:
          REDIS_URL: ${{ secrets.REDIS_URL }}
          SUPABASE_S3_ENDPOINT: ${{ secrets.S3_ENDPOINT }}
          SUPABASE_S3_REGION: ${{ secrets.S3_REGION }}
          SUPABASE_S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
          SUPABASE_S3_SECRET_KEY: ${{ secrets.S3_SECRET_KEY }}
        
        run: make run-scraping